name: tuneisappflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #tflite_flutter: ^0.10.4
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_fonts: ^4.0.4
  pytorch_lite: ^4.3.2
  onnxruntime: ^1.0.0  # Versão mais recente
  image: ^4.1.4
  http: ^1.3.0
  path_provider: ^2.1.2
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/drone.png

