name: tuneisapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  http_parser: ^4.0.2
  path_provider: ^2.1.5
  video_player: ^2.9.1
  photo_view: ^0.15.0
  archive: ^3.6.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/drone.png
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf